### ISSUE TITLE
Hand Location Tracker

### ISSUE THREAD

**Issue by thomaskost17** [180D-FW-2020/Team8#10]
- [ ] determine proper masking method for different skin tones
- [ ] convex hull investigation
- [ ] Center of mass function
- [ ] number of fingers function
- [ ] open vs closed function
- [ ] finger tip location function
- [ ] hand vs. no hand boolean function
