### ISSUE TITLE
project package

### ISSUE THREAD

**Issue by n8atnite** [180D-FW-2020/Team8#61]
A package for MEAT must contain source libraries, testable examples, and documentation on how to use.

- [ ] package creation - file structure, dependency handling, setup.py (distribution using distutils)
- [ ] example schema agreed upon -> create new issue for example design
- [ ] documentation for testers

**Comment by n8atnite** [comment]
https://www.geeksforgeeks.org/source-distribution-and-built-distribution-in-python/

**Comment by nzani** [comment]
Add: current test_app.py must be run from a particular directory; would be best if filepaths could be resolved at runtime instead of hard-coded.
