### ISSUE TITLE
mqtt chatbox

### ISSUE THREAD

**Issue by n8atnite** [180D-FW-2020/Team8#62]
features to implement:

- [x]  emotes - special strings sent in chat spawn animations on receivers' screen

- [ ]  homography sync - share and edit objects together

- [ ] games - possible interesting use case for imgproc/mqtt/gestures

**Comment by n8atnite** [comment]
game requirements:

- turn-based
- game data over mqtt
- game launch over mqtt (as separate connection or over same connection)
- gesture integration

**Comment by n8atnite** [comment]
other use cases:

- embedded links; simple cases (no media players) like pulling wiki results
- dedicated services; weather info, translations, etc.

Let's take inspiration from widgets in Messenger, discord bots, etc. as ideas to implement and expand to use homography/gestures/STT

**Comment by nzani** [comment]
@n8atnite are you sure this is closed? not sure this is functional yet..

**Comment by n8atnite** [comment]
i did not close it idk why it said i did
